services:
  app:
    build: .
    ports:
      - "8081"
    environment:
      - REDIS_HOST=cache
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_MODEL=${OPENAI_MODEL}

  cache:
    image: redis:7-alpine
